function varargout = SurfRecShare( )
%share of heat generated by surface recombination in total facet heating
%calculated according to Fig. 1 [Ziegler et al. 2008 Appl. Phys. Lett. 92 203506]

global alpha b c current currentth dsur D elcharge factor A gamma hbar J K  lambda L M Pout R tau...
    vg v0 w wavelength ybottom yinterface ytop z0

deltaith = currentth - 1.0; %threshold current need not be equal to unity as in Fig.1 [Ziegler et al.]
totheat = (current - deltaith) +0.5; %total heat (curve 'facet temperature as measured' in Fig.1 [Ziegler et al.])
surfrec = 0.75; % surface recombination contribution

surfrecshare = surfrec/totheat;

varargout{1} = surfrecshare;


